[package]
name = "aliyun-oss-figure-bed"
version = "0.1.7"
edition = "2024"

[dependencies]
aliyun-oss-client = "0.12"
tokio = { version = "1.49.0", features = ["full"] }
chrono = "0.4.43"
uuid = { version = "1.21.0", features = ["v4"] }
futures = "0.3.32"
